### ISSUE TITLE
Broken padding/margin for list-cards.

### ISSUE THREAD

**Issue by aydencook03** [kepano/obsidian-minimal-publish#11]
The gap around list-cards is too large, especially on the left side. I am using the flexoki color-palette. The image below shows the issue.

![image (1)](https://github.com/user-attachments/assets/76282156-c4bf-463c-bc2c-4d8645eaa339)

Pasting the following code-block to the bottom of the `publish.css` file fixed the problem.

```css
.list-cards.markdown-preview-view ul {
  margin: 1em 0 0 0;
  padding: 0;
  list-style: none;
}

.list-cards.markdown-preview-view li {
  margin: 0;
  padding: 0;
}
```

With this fix, it now looks like this:

![image](https://github.com/user-attachments/assets/853abe8a-6ae9-4493-86c5-7d16e64857cb)
